services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - calendar_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - calendar_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrator:
    image: golang:1.23
    working_dir: /app
    volumes:
      - .:/app
    command: make migrate
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - calendar_net

  calendar:
    build:
      context: .
      dockerfile: build/Dockerfile
    command: ./bin/calendar --config=/configs/calendar_config.yaml
    working_dir: /opt/calendar
    volumes:
      - ./configs:/configs
    depends_on:
      migrator:
        condition: service_completed_successfully
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - calendar_net

  calendar_scheduler:
    build:
      context: .
      dockerfile: build/Dockerfile
    command: ./bin/calendar_scheduler --config=/configs/scheduler_config.yaml
    working_dir: /opt/calendar
    volumes:
      - ./configs:/configs
    depends_on:
      migrator:
        condition: service_completed_successfully
    restart: on-failure
    networks:
      - calendar_net

  calendar_sender:
    build:
      context: .
      dockerfile: build/Dockerfile
    command: ./bin/calendar_sender --config=/configs/sender_config.yaml
    working_dir: /opt/calendar
    volumes:
      - ./configs:/configs
    depends_on:
      migrator:
        condition: service_completed_successfully
    restart: on-failure
    networks:
      - calendar_net

  integration-tests:
    image: golang:1.23
    volumes:
      - .:/app
    working_dir: /app
    command: go test -v ./tests/integration/...
    depends_on:
      - calendar
      - calendar_scheduler
      - calendar_sender
    networks:
      - calendar_net

volumes:
  pgdata:

networks:
  calendar_net:
