logger:
  level: debug

rabbitmq:
  uri: amqp://guest:guest@rabbitmq:5672/
  queue: events

system:
  database:
    enable: true
    host: "postgres"
    port: 5432
    db_name: "postgres"
    scheme: "calendar"
    user: "postgres"
    password: "postgres"
    timeout: 5
    ssl_mode: disable

scheduler:
  interval: 10s
